name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
        laravel: [5.8.*, 6.*, 7.*, 8.*, 9.*]
        include:
          - laravel: 5.8.*
            testbench: 3.8.*
            phpunit: ^7.5
            phpunit_printer: 'Sempro\PHPUnitPrettyPrinter\PrettyPrinter'
          - laravel: 6.*
            testbench: 4.*
            phpunit: ^8
            phpunit_printer: 'Sempro\PHPUnitPrettyPrinter\PrettyPrinter'
          - laravel: 7.*
            testbench: 5.*
            phpunit: ^8
            phpunit_printer: 'Sempro\PHPUnitPrettyPrinter\PrettyPrinter'
          - laravel: 8.*
            testbench: 6.*
            phpunit: ^9.5.10
            phpunit_printer: 'Sempro\PHPUnitPrettyPrinter\PrettyPrinterForPhpUnit9'
          - laravel: 9.*
            testbench: 7.*
            phpunit: ^9.5.10
            phpunit_printer: 'Sempro\PHPUnitPrettyPrinter\PrettyPrinterForPhpUnit9'
        exclude:
          - laravel: 5.8.*
            php: 8.0
          - laravel: 5.8.*
            php: 8.1
          - laravel: 6.*
            php: 8.1
          - laravel: 7.*
            php: 8.1
          - laravel: 8.*
            php: 7.2
          - laravel: 9.*
            php: 7.2
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction
      - name: Execute tests
        run: php vendor/bin/phpunit --printer "${{ matrix.phpunit_printer }}" tests/
